### ISSUE TITLE
Cleaning up doesn't work

### ISSUE THREAD

**Issue by bergus** [rtm/cancelable-promise#1]
The executor cannot return a promise as `onCancel`, as a promise runs immediately. You probably rather want to return a function, like [here](https://github.com/domenic/cancelable-promise/blob/master/New%20Ideas%20Brainstorming.md#adapting-old-apis) or [there](https://github.com/bergus/promise-cancellation/blob/master/examples.md#creation-of-cancellable-promises)

**Comment by rtm** [comment]
Relates to earlier version--closing.
