### ISSUE TITLE
CancelNow?

### ISSUE THREAD

**Issue by bergus** [rtm/cancelable-promise#2]
The readme doesn't really make clear what this method does or what it is used for.
It seems however to be a method on every promise that immediately rejects it, which is a no-go - promises must be immutable from outside.

**Comment by rtm** [comment]
Poorly named. This does not attempt to mutate the promise or cancel it now. It applies only to promises used as cancelers. It means only that any promise created with a canceler on which this method has been called will never even start and will immediate be thrown into a canceled state. Now renamed to `precancel`, which is probably not a much better name.

**Comment by bergus** [comment]
OK, so it's only the promises that got a canceller passed into them, but still a method that "immediately throws them into a cancelled state" does sound like it's mutating the promise state from outside. Only the creator of the promise should be allowed to do that.
And do you mean by "_will never even start_"? A promise represents not an operation but its result, the operation starts when the promise is created.

**Comment by rtm** [comment]
Relates to earlier version--closing.
